### PR TITLE
Update nodedump.js

### PR DESCRIPTION
**Pull request by AckerApple**
adds showFuncs attribute that works like showUDFs for cfDump

Much prefer verbiage showFuncs over showUDFs

### CODE REVIEW

**Comment by ragamufin** [comment]
I'm in Brazil at the moment watching the World Cup :) Thanks for your hard work though, I'll check this as soon as I have a moment.

**Comment by AckerApple** [comment]
Thanks for getting back to me, thought maybe I flooded your email with me learning.

I would like to make another pull request here soon, to fix displaying arrays with a length of 10 or greater. When an array length is greater than 9, the display order is: 1,10,2,3,4,5,6,7,8,9

Thank you friend. Do stay in-touch as I would enjoy doing more work knowing it’s being looked at (even if modified or not used)

**Comment by ragamufin** [comment]
No problem. For the showFuncs option I was thinking it would be nice to show the functions collapsed instead of hiding them altogether. Didn't know about arrays when they are longer than 10. I'll check up on your code when I can. In the next week or so.

**Comment by AckerApple** [comment]
I here you about collapsing functions but here is my two sense:
1. ColdFusion & Railo completely remove functions when showUDFs=false
2. A performance boost is gained from not dumping functions
3. perhaps showFuncs could also accept an argument value of "collapse"

Thank you kindly

**Comment by ragamufin** [comment]
Good points. I'll check it out and let you know.
- Andrew

**Comment by ragamufin** [comment]
Hi, it's been a while. I'm still loitering around Brazil but with the World Cup finished and me finally firing up the pc to get some work done I was finally able to look at this. Looking at the changes you made I realized that it didn't take into account the "filtering" text that shows up whenever you hide keys using options such as 'hide' or 'show'. I kind of like having that there to let you know that the Functions are being hidden. I also thought it would be nice to be able to collapse them like I said before but as you rightly said we should still be able to hide them altogether. I also thought that if we want to do this for functions, it might be nice to make it generic to work for other types as well, such as process objects that tend to be huge. 

Anyway, I just committed some changes if you don't mind taking a look. In the options (https://github.com/ragamufin/nodedump#options) now there are `hideTypes` and `collapse`. By passing in `hideTypes: ['function']` you can hide them from the output. There will be some text in the label letting you know how many functions were in fact hidden. You can hide any other complex types as well, such as arrays, regexp, what-have-you.

`Collapse` works opposite from `expand`. You could pass in `collapse: ['function']` for instance and all functions would be collapsed. 

Let me know what you think.

**Comment by AckerApple** [comment]
These changes sound great. I will review later today. I noticed my Github account has a contribution now, so couldn't be happier

Thank you kindly friend

**Pull request closed without merging**
